# Generated by Django 4.0.4 on 2022-06-01 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_handroll_proteina_remove_handroll_vegetal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desayuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proteinadesayuno')),
                ('queso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quesodesayuno')),
                ('vegetal1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desayuno.vegetal1+', to='core.vegetalesdesayuno')),
                ('vegetal2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desayuno.vegetal2+', to='core.vegetalesdesayuno')),
            ],
        ),
    ]
