# Generated by Django 4.0.4 on 2022-06-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_desayuno'),
    ]

    operations = [
        migrations.AddField(
            model_name='almuerzo',
            name='typ',
            field=models.CharField(default='al', max_length=50),
        ),
        migrations.AddField(
            model_name='desayuno',
            name='typ',
            field=models.CharField(default='des', max_length=50),
        ),
        migrations.AddField(
            model_name='handroll',
            name='typ',
            field=models.CharField(default='h', max_length=50),
        ),
        migrations.AddField(
            model_name='handrollready',
            name='typ',
            field=models.CharField(default='hc', max_length=50),
        ),
        migrations.AddField(
            model_name='kai',
            name='typ',
            field=models.CharField(default='kai', max_length=50),
        ),
        migrations.AddField(
            model_name='selladitas',
            name='typ',
            field=models.CharField(default='sell', max_length=50),
        ),
    ]
