# Generated by Django 4.0.4 on 2022-06-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bowl_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('cooking', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('article', models.ManyToManyField(to='core.article')),
            ],
        ),
    ]
