# Generated by Django 4.0.4 on 2022-06-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_comanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='cod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
