# Generated by Django 4.0.4 on 2022-06-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comanda_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='time_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='time_to_kitchen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
