# Generated by Django 4.0.4 on 2022-06-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comanda_time_finished_comanda_time_to_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='handrollready',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
