# Generated by Django 4.0.4 on 2022-06-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_comanda_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
