# Generated by Django 4.0.4 on 2022-06-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_comanda_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='almuerzo',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bowl',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='desayuno',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='handroll',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='handrollready',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kai',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='selladitas',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
